// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/25/2025, 8:02:53 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/Users/daniel1ruuth/workspace/ancestors/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/plugins/**/*.{js,ts,mjs}","/Users/daniel1ruuth/workspace/ancestors/composables/**/*.{js,ts,mjs}","/Users/daniel1ruuth/workspace/ancestors/utils/**/*.{js,ts,mjs}","/Users/daniel1ruuth/workspace/ancestors/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/daniel1ruuth/workspace/ancestors/app.config.{js,ts,mjs}","/Users/daniel1ruuth/workspace/ancestors/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;